name: Deploy to EC2-dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-development:
    name: Push to EC2 (dev)
    runs-on: ubuntu-latest 
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: ./deploy-dev.sh